### ISSUE TITLE
Google Map broken

### ISSUE THREAD

**Issue by LondonRain** [cahz/komoot-unlocked-regions#5] opened 2022-12-08 14:53 UTC
The generated google map is broken in tiles all over the place and the regions do not longe appear on it.
![grafik](https://user-images.githubusercontent.com/33151586/206478084-2064007f-64a6-4e82-a352-1bc5fb48ebed.png)

Tested in Chrome and Edge.

**Comment by WuerfelDev** [comment] 2022-12-08 15:03
I don't have a way to test and reproduce it currently, but it shouldn't be related to this code. Looks like a bug elsewhere, maybe https://github.com/Leaflet/Leaflet/ (?)

**Comment by frankcom** [comment] 2023-01-01 09:51
Unfortunately same here, how can we help finding out the issue?
Tested in Firefox and Chrome.

**Comment by cahz** [comment] 2023-01-03 17:06
I found the issue and pushed my changes. The problem was that I did not load the leaflet stylesheet. Interesting that it was working before...

**Comment by frankcom** [comment] 2023-01-03 17:45
Hi, thanks for working on the problem.
I confirm that it is perfect in Chrome now.
For my side there are still errors in Firefox 108.
I attach a txt log.
All the best for 2023
Frank
[console-export-2023-1-3_18-42-22.txt](https://github.com/cahz/komoot-unlocked-regions/files/10338677/console-export-2023-1-3_18-42-22.txt)

**Comment by cahz** [comment] 2023-09-14 18:12
Should be fixed now. Please reopen if this is still relevant.

**Closed as completed by cahz** 2023-09-14 18:12 UTC
